version: '3.7'

services:
  asterisk:
    container_name: asterisk16
    image: asterisk16:latest
    restart: always
    ports:
      - 5060:5060/udp
      - 5061:5061
      - 8088:8088
      - 8089:8089
      - 18000-18100:18000-18100/udp
    volumes:
      - ./conf:/etc/asterisk
      - ./static-http:/var/lib/asterisk/static-http
      - ./certs:/etc/certs:rw
    networks:
      net:
        ipv4_address: 172.25.0.10
    logging:
      options:
        max-size: 100M

networks:
  net:
    external: true